apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-backup
  namespace: kube-ops
spec:
  capacity:
    # only suitable for production
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "gluster-cluster"
    path: "mongo_backup"
    readOnly: false

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-backup
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # only suitable for production
      storage: 500Gi

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: kube-ops
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      # backoffLimit: 5
      # activeDeadlineSeconds: 100
      # concurrencyPolicy: Replace
      template:
        spec:
          containers:
          - name: mongo-backup
            image: registry.ipt-gitlab:8081/ta-web/sit-db-mongo/mongo-backup-client:__VERSION__      
            args:
            - /bin/bash
            - -c
            - "cd /root/ && bash mongo-cluster-backup.sh"
            volumeMounts:
            - mountPath: /data/backup
              name: mongo-backup
            - mountPath: /etc/localtime
              name: tz-config
          restartPolicy: OnFailure
          # hostNetwork: true
          volumes:
          - name: tz-config
            hostPath:
              path: /usr/share/zoneinfo/Asia/Shanghai
          - name: mongo-backup
            persistentVolumeClaim:
              claimName: mongo-backup
          imagePullSecrets:
          - name: gitlab-registry
